Adapt autoconf scripts to boost 1.38

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -26,54 +26,58 @@ AC_ARG_WITH(boost-include,
             if test [ x$withval != x ] -a [ -d $withval ]; then
             BOOST_INCLUDE_DIR=$withval
             else
-            echo "Please specify a suitable PCRE include directory: --with-pcre-include=DIR"; exit 1
+            echo "Please specify a suitable BOOST include directory: --with-boost-include=DIR"; exit 1
             fi ,
-            BOOST_INCLUDE_DIR="/usr/include/boost")
+            BOOST_INCLUDE_DIR="/usr/include")
 
 dnl BOOST lib dir
 AC_ARG_WITH(boost-lib,
             [--with-boost-lib=path of BOOST lib],
             if test [ x$withval != x ] -a [ -d $withval ]; then
-	    BOOST_LIB_DIR="-L"$withval;
 	    [LDFLAGS="${LDFLAGS} -L${withval}"]
             else
-            echo "Please specify a suitable PCRE library directory: --with-pcre-lib=DIR"; exit 1
+            echo "Please specify a suitable BOOST library directory: --with-boost-lib=DIR"; exit 1
             fi ,
 	    )
 
 dnl check boost graph library include
-AC_CHECK_FILE($BOOST_INCLUDE_DIR/graph/adjacency_list.hpp, ,
+AC_CHECK_FILE($BOOST_INCLUDE_DIR/boost/graph/adjacency_list.hpp, ,
               echo "BOOST include directory does not contain the Boost Graph Library !";
               echo "Please specify a suitable BOOST include directory: --with-boost-include=DIR"; exit 1)
 
 dnl check boost tokenizer include
-AC_CHECK_FILE($BOOST_INCLUDE_DIR/tokenizer.hpp, ,
+AC_CHECK_FILE($BOOST_INCLUDE_DIR/boost/tokenizer.hpp, ,
               echo "BOOST include directory does not contain the Tokenizer Library !";
               echo "Please specify a suitable BOOST include directory: --with-boost-include=DIR"; exit 1)
 
 dnl check boost lexical cast include
-AC_CHECK_FILE($BOOST_INCLUDE_DIR/lexical_cast.hpp, ,
+AC_CHECK_FILE($BOOST_INCLUDE_DIR/boost/lexical_cast.hpp, ,
               echo "BOOST include directory does not contain the Lexical Cast Library !";
               echo "Please specify a suitable BOOST include directory: --with-boost-include=DIR"; exit 1)
 
 dnl check boost filesystem include
-AC_CHECK_FILE($BOOST_INCLUDE_DIR/filesystem/path.hpp, ,
+AC_CHECK_FILE($BOOST_INCLUDE_DIR/boost/filesystem/path.hpp, ,
               echo "BOOST include directory does not contain the Filesystem Library !";
+	      echo "$BOOST_INCLUDE_DIR/boost/filesystem/path.hpp not found";
               echo "Please specify a suitable BOOST include directory: --with-boost-include=DIR"; exit 1)
 
 AC_SUBST(BOOST_INCLUDE_DIR)
-
-dnl BOOST filesystem library
-AC_CHECK_LIB(boost_filesystem,
-	     main,
-	     [LDFLAGS="${LDFLAGS} -lboost_filesystem"],
-	     echo "libboost_filesystem not found. Please add BOOST library directory to your LD_LIBRARY_PATH or specify a suitable BOOST library directory: --with-boost-lib=DIR"; exit 1)
 
 dnl BOOST program options library
 AC_CHECK_LIB(boost_program_options,
 	     main,
 	     [LDFLAGS="${LDFLAGS} -lboost_program_options"],
 	     echo "libboost_program_options not found. Please add BOOST library directory to your LD_LIBRARY_PATH or specify a suitable BOOST library directory: --with-boost-lib=DIR"; exit 1)
+
+dnl BOOST filesystem library
+AC_CHECK_LIB(boost_system,
+	     main,
+	     [LDFLAGS="${LDFLAGS} -lboost_system"])
+
+AC_CHECK_LIB(boost_filesystem,
+	     main,
+	     [LDFLAGS="${LDFLAGS} -lboost_filesystem"],
+	     echo "libboost_filesystem not found. Please add BOOST library directory to your LD_LIBRARY_PATH or specify a suitable BOOST library directory: --with-boost-lib=DIR"; exit 1)
 
 AC_SUBST(BOOST_LIB_DIR)
 
